### ISSUE TITLE
What UML Diagrams to Use?

### ISSUE THREAD

**Issue by bgvmysore** [yasirfaizahmed/SDLC_2_Electron#1]
## What are the 8 UMLs diagrams we are going to use?
We need **4 UMLs for High Level Design and 4 UMLs for Low Level Design**.

**Comment by bgvmysore** [comment]
Please **leave a comment** saying which UMLs we are going to use

**Comment by 263998** [comment]
we have used use case, activity, for high level and flowchart for low level

**Comment by Saurav225** [comment]
use case, flowchart of all levels

**Comment by Swathir1** [comment]
for high level design, we can add activity diagram, usecase diagram.
for low level design, we can add flowchart, object diagram.

**Comment by Annappa259804** [comment]
Usecase UML for High level Design
